### ISSUE TITLE
ValueError: You are trying to load a weight file containing 5 layers into a model with 7 layers.

### ISSUE THREAD

**Issue by prince4547** [smearle/gym-micropolis#2]
Hi,

When i am trying to run learn.py either test or train, i am getting the above error. Can you please help me with the same. My keras Version 2.2.4.Below is the exact error i am getting.

Thanks
Prince

=================================================================
Total params: 262,057
Trainable params: 262,057
Non-trainable params: 0
_________________________________________________________________
None
Traceback (most recent call last):
  File "learn.py", line 179, in <module>
    dqn.load_weights(args.weights)
  File "/usr/lib/python2.7/site-packages/rl/agents/dqn.py", line 209, in load_weights
    self.model.load_weights(filepath)
  File "/usr/lib64/python2.7/site-packages/keras/models.py", line 733, in load_weights
    topology.load_weights_from_hdf5_group(f, layers)
  File "/usr/lib64/python2.7/site-packages/keras/engine/topology.py", line 3115, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 5 layers into a model with 7 layers.

**Comment by smearle** [comment]
Hey Prince, sorry for the long delay. I've cleaned up the repo so that it includes the agent I'm currently using to train on this environment. Run main.py as described in the updated readme.

Thank you for your interest!
